### PR TITLE
Add underline and colour to hyperlink text

### PR DESCRIPTION
**Pull request by pavithraes**
## Reference Issues or PRs

#18 

"the documentation" is inactive link

"Nebari support forums" is active link (the underline is offset)

Screenshot 2023-07-06 at 1 44 04 AM

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [ ] This content adheres to the Nebari style guides.

#### Non-text content

- [ ] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If the content were to be read as plain text, it still makes sense, and no information is missing.

### CODE REVIEW

**Comment by pavithraes** [comment]
(This comment is a non-blocker for this PR)

I also see `--text-color` and `--link-text-color` are the same, maybe we can set a new `--link-text-color`?

https://github.com/nebari-dev/nebari-jupyterhub-theme/blob/71f049adf41d681b50a261373a6ee2c75c64da15/nebari_jupyterhub_theme/templates/style.css#L35-L36

**Review by iameskild — APPROVED** [review]
> (This comment is a non-blocker for this PR)
> 
> I also see `--text-color` and `--link-text-color` are the same, maybe we can set a new `--link-text-color`?
> 
> https://github.com/nebari-dev/nebari-jupyterhub-theme/blob/71f049adf41d681b50a261373a6ee2c75c64da15/nebari_jupyterhub_theme/templates/style.css#L35-L36

Yeah I think you're right that it makes sense to make the `--link-text-color` a different color. Feel free to include it in this PR if you'd like.

**Comment by pavithraes** [comment]
> Yeah I think you're right that it makes sense to make the --link-text-color a different color. Feel free to include it in this PR if you'd like.

Okay, thanks! Made it the same as the on-hover colour :)

**Comment by pavithraes** [comment]
I'll go ahead and merge, we an update the colours / behaviour later is needed. :)

**Pull request merged**
